image:
  repository: gcr.io
  name: kuar-demo/kuard-amd64
  version: 1

replicaCount: 2

nameOverride: ""
fullnameOverride: ""

service:
  port: 8080
  startup:
    waitSeconds: 10
  liveness:
    path: /healthy
    timeoutSeconds: 1
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /ready
    timeoutSeconds: 1
    periodSeconds: 10
    failureThreshold: 3

ingress-nginx:
  controller:
    ingressClass: nginx
    service:
      externalTrafficPolicy: Local
      loadBalancerIP: 127.0.0.1

ingress:
  enabled: true
  host: localhost
  limitConnections: 10
  limitRps: 1

resources:
  requests:
    cpu: 100m
    memory: 10Mi
  limits:
    cpu: 200m
    memory: 20Mi